server:
  port: 80


spring:
  application:
    name: consumer-client
  datasource:
    type: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql:localhost:3306/spring_cloud_db?useUnicode=ture&characterEncoding=UTF-8
    username: root
    password: 123456