server:
  port: 80

spring:
  application:
    name: EUREKA-CONSUMER

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka, http://localhost:8001/eureka